### PR TITLE
Addressed the comments for issue #21 (Fix was given by @Medex81)

### PR DESCRIPTION
**Pull request by rameshrvr**

### CODE REVIEW

**Comment by rameshrvr** [comment]
Hey @russellballestrini , i've addressed the comments for PR #24 and added few more tests as well. Please review.

**Comment by rameshrvr** [comment]
CI results.

- Python3
```ruby
ramesh_rv$ pytest
================================================================= test session starts =================================================================
platform darwin -- Python 3.7.0, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /Users/ramesh_rv/Documents/Github/python_packages/nested-lookup
collected 49 items                                                                                                                                    

test_lookup_api.py ............................                                                                                                 [ 57%]
test_nested_lookup.py .....................                                                                                                     [100%]

============================================================== 49 passed in 0.16 seconds ==============================================================
```

- Python2
```ruby
ramesh_rv$ python -m unittest test_nested_lookup test_lookup_api
.................................................
----------------------------------------------------------------------
Ran 49 tests in 0.005s

OK
```

**Comment by rameshrvr** [comment]
Hey @russellballestrini This PR hasn't been reviewed for a while. Can you please review and merge this??? Also can you please release the latest version to PyPi

**Comment by rameshrvr** [comment]
CI results:
```
:nested-lookup rameshrv$ python -m unittest test_nested_lookup test_lookup_api
..................................................
----------------------------------------------------------------------
Ran 50 tests in 0.004s

OK
:nested-lookup rameshrv$ pytest
========================================================================= test session starts =========================================================================
platform darwin -- Python 3.7.4, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /Users/rameshrv/Documents/GitHub/nested-lookup
collected 50 items                                                                                                                                                    

test_lookup_api.py .............................                                                                                                                [ 58%]
test_nested_lookup.py .....................                                                                                                                     [100%]

========================================================================= 50 passed in 0.07s ==========================================================================
:nested-lookup rameshvrv$ 
````

**Comment by russellballestrini** [comment]
@rameshrvr  could you please resolve conflicts by rebasing this PR with master? Screenshot from 2019-10-31 08-18-51

**Comment by rameshrvr** [comment]
@russellballestrini For me its showing there are no conflicts.
Screenshot 2019-10-31 at 5 51 07 PM

**Comment by russellballestrini** [comment]
I think the master branch on your fork is stale and that's why it's not showing conflicts for you.

stale

**Comment by russellballestrini** [comment]
closing for now because we accepted https://github.com/russellballestrini/nested-lookup/pull/26

**Pull request closed without merging**
